
runtime: python37
service: default
instance_class: B1
basic_scaling:
  max_instances: 25
  idle_timeout: 5m

# entrypoint: app.py
# entrypoint: gunicorn -b :$PORT main:app
handlers:
- url: /poke-profile.html
  script: poke-profile.app

  - url: /query.html
  script: query.app

  - url: /
  script: auto